# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: (^placeholders/|^tests/test_files/)
    -   id: end-of-file-fixer
        exclude: (^placeholders/|^tests/test_files/)
    -   id: check-yaml
        exclude: (^placeholders/|^tests/test_files/)
    -   id: check-added-large-files
        exclude: (^placeholders/|^tests/test_files/)
