# AMA-316 Config for list of restricted files
# https://community.brightspace.com/s/article/KBL931002031

RESTRICTED_EXT:
  ASA: "ASA file"
  ASAX: "ASAX file"
  ASCX: "ASCX file"
  ASHX: "ASHX file"
  ASMX: "ASMX file"
  ASP: "ASP file"
  ASPX: "ASPX file"
  AXD: "AXD file"
  BAT: "BAT file"
  CDX: "CDX file"
  CER: "CER file"
  COM: "COM file"
  CONFIG: "CONFIG file"
  CS: "CS file"
  CSPROJ: "CSPROJ file"
  DLL: "DLL file"
  EXE: "EXE file"
  IDC: "IDC file"
  INI: "INI file"
  JSL: "JSL file"
  LICX: "LICX file"
  M3U: "M3U Audio playlist"
  M3U8: "M3U Audio playlist"
  PL: "PL file"
  REM: "REM file"
  RESOURCES: "RESOURCES file"
  RESX: "RESX file"
  SHTM: "SHTM file"
  SHTML: "SHTML file"
  SOAP: "SOAP file"
  STM: "STM file"
  VB: "VB file"
  VBPROJ: "VBPROJ file"
  VJSPROJ: "VJSPROJ file"
  VSDISCO: "VSDISCO file"
  WEBINFO: "WEBINFO file"

# AMA-552 Supported media formats
# https://community.d2l.com/brightspace/kb/articles/3442-audio-video-file-types-supported-in-brightspace
SUPPORTED_AUDIO:
  MP3: "MP3 audio"
  M4A: "M4A audio"
  OGG: "OGG audio"
  WAV: "WAV audio"
  WMA: "WMA audio"

SUPPORTED_VIDEO:
  MP4: "MP4 video"
  AVI: "AVI video"
  F4V: "F4V video"
  FLV: "FLV video"
  M4V: "M4V video"
  MOV: "MOV video"
  WEBM: "WEBM video"
  WMV: "WMV video"
