STEPS:

  # LTI Quicklinks
  # - action: create_lti_quicklinks

  # Set the reference site to inactive
  - action: update_refsite
    use_import_id: 1

  # Creata a Q&A module and topic
  - action: push_qna_topic
    use_import_id: 1

  # Updated embedded media identifiers
  - action: check_for_placeholders
    use_import_id: 1
    use_transfer_id: 1

  # Remove modules that we added to content
  - action: cleanup_modules
    use_import_id: 1

  # Upload rubrics zip if present
  - action: push_rubrics
    use_import_id: 1
    use_transfer_id: 1
    use_title: 1

  # Add users to the reference site
  - action: enroll_users
    use_import_id: 1

  # Create a new empty site if selected and enroll users
  - action: create_course_offering
    use_link_id: 1

  # Finish up
  - action: mail
    template: 'finished'
    subject: 'Vula to Amathuba: Finished [{{ title }}]'
    state: 'completed'

  - action: set_site_property
    conversion_success: 1
    conversion_status: 'success'

  # Remove working files
  - action: cleanup
